### ISSUE TITLE
Issues not yet addressed?

### ISSUE THREAD

**Issue by Vikas2004** [SaiGorla/Talk2-group06#2]
The app is still incomplete and the bug is still not addressed. There is no google analytics added to it, The footer needs to be fixed. All these issues are to be addressed. Where are we lagging with these? Try and solve them ASAP.

**Comment by sumanthreddy1233** [comment]
yeah, will work on it.

**Comment by sumanthreddy1233** [comment]
Added google analytics and the link is added to the footer
